### ISSUE TITLE
Caching\MemoryCacheBase.cs System.ArgumentOutOfRangeException: The relative expiration value must be positive. (Parameter 'AbsoluteExpirationRelativeToNow')

### ISSUE THREAD

**Issue by tung-nt-niteco** [grandnode/grandnode2#438]
Unhandled exception. System.ArgumentOutOfRangeException: The relative expiration value must be positive. (Parameter 'AbsoluteExpirationRelativeToNow')
Actual value was 00:00:00.
   at Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions.set_AbsoluteExpirationRelativeToNow(Nullable`1 value)
   at Grand.Infrastructure.Caching.MemoryCacheBase.GetMemoryCacheEntryOptions(Int32 cacheTime) in \src\Core\Grand.Infrastructure\Caching\MemoryCacheBase.cs:line 158

**Comment by KrzysztofPajak** [comment]
Yes, cache is invalidated when data has been changed
